In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


In [2]:
path = 'C:/Users/Dell/Downloads/MobilePriceClassification/MobilePriceClassification/'
train = pd.read_csv(path+'train.csv')
test = pd.read_csv(path+'test.csv')

In [3]:
train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [14]:
train.price_range.unique()

array([1, 2, 3, 0], dtype=int64)

In [4]:
from sklearn.model_selection import train_test_split
X = train.drop(columns=['price_range'])
y = train[['price_range']].values
y = y.ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [7]:
from sklearn.model_selection import GridSearchCV 
from sklearn import svm

# defining parameter range 
param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'kernel': ['rbf']}  
  
grid = GridSearchCV(svm.SVC(), param_grid, refit = True, verbose = 3) 
  
# fitting the model for grid search 
grid.fit(X_train, y_train) 
# print best parameter after tuning 
print(grid.best_params_) 
  
# print how our model looks after hyper-parameter tuning 
print(grid.best_estimator_) 

C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s


Fitting 3 folds for each of 25 candidates, totalling 75 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.253, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.254, total=   0.2s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.255, total=   0.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.3s remaining:    0.0s


[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.253, total=   0.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.254, total=   0.2s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.255, total=   0.2s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.253, total=   0.2s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.254, total=   0.2s
[CV] C=0.1, gamma=0.01, kernel=rbf ...................................
[CV] ....... C=0.1, gamma=0.01, kernel=rbf, score=0.255, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] ...... C=0.1, gamma=0.001, kernel=rbf, score=0.253, total=   0.2s
[CV] C=0.1, gamma=0.001, kernel=rbf ..................................
[CV] .

[CV] ......... C=1000, gamma=1, kernel=rbf, score=0.255, total=   0.2s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.253, total=   0.2s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.254, total=   0.2s
[CV] C=1000, gamma=0.1, kernel=rbf ...................................
[CV] ....... C=1000, gamma=0.1, kernel=rbf, score=0.255, total=   0.2s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.253, total=   0.2s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.254, total=   0.2s
[CV] C=1000, gamma=0.01, kernel=rbf ..................................
[CV] ...... C=1000, gamma=0.01, kernel=rbf, score=0.255, total=   0.2s
[CV] C=1000, gamma=0.001, kernel=rbf .................................
[CV] .

[Parallel(n_jobs=1)]: Done  75 out of  75 | elapsed:   11.3s finished


{'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}
SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [13]:
clf = grid.best_estimator_ #tree_cv.best_estimator_ #

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_train)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_train, y_pred))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_train, y_pred))

y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_test, y_pred))
print("Mean_Squared_Error:",metrics.mean_squared_error(y_test, y_pred))


Accuracy: 1.0
F1_Score: 1.0
F1_Score: 1.0
F1_Score: 1.0
Confusion Metrics: [[381   0   0   0]
 [  0 374   0   0]
 [  0   0 373   0]
 [  0   0   0 372]]
Accuracy: 0.666
F1_Score: 0.666
F1_Score: 0.6770654487623556
F1_Score: 0.6780706617437311
Confusion Metrics: [[117   2   0   0]
 [ 51  71   4   0]
 [ 46   3  73   5]
 [ 48   0   8  72]]
Mean_Squared_Error: 1.378


In [15]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = neigh.predict(X_train)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_train, y_pred))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_train, y_pred))

y_pred = neigh.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_test, y_pred))
print("Mean_Squared_Error:",metrics.mean_squared_error(y_test, y_pred))


Accuracy: 0.9433333333333334
F1_Score: 0.9433333333333332
F1_Score: 0.9432389830630539
F1_Score: 0.9433586196331614
Confusion Metrics: [[377   4   0   0]
 [ 21 349   4   0]
 [  0  21 349   3]
 [  0   0  32 340]]
Accuracy: 0.898
F1_Score: 0.898
F1_Score: 0.8982154070524907
F1_Score: 0.8977714168631596
Confusion Metrics: [[117   2   0   0]
 [ 15 109   2   0]
 [  0  13 110   4]
 [  0   0  15 113]]
Mean_Squared_Error: 0.102


In [24]:
y_pred2 = neigh.predict(test.drop(columns=['id']))

In [25]:
test['price_range'] = y_pred2
test = test[['id','price_range']]
test.to_csv('Mobile_price_prediction.csv')

In [17]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression().fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_train)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_train, y_pred))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_train, y_pred))

y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_test, y_pred))
print("Mean_Squared_Error:",metrics.mean_squared_error(y_test, y_pred))


Accuracy: 0.806
F1_Score: 0.806
F1_Score: 0.7991453190211436
F1_Score: 0.7996832636139968
Confusion Metrics: [[365  13   3   0]
 [ 42 243  89   0]
 [  0  69 238  66]
 [  0   0   9 363]]
Accuracy: 0.764
F1_Score: 0.764
F1_Score: 0.7553224673132868
F1_Score: 0.7537190551553399
Confusion Metrics: [[117   1   1   0]
 [ 25  70  31   0]
 [  0  39  72  16]
 [  0   0   5 123]]
Mean_Squared_Error: 0.242


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [32]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth = 9)
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_train)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_train, y_pred))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_train, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_train, y_pred))

y_pred = clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'micro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'macro'))
print("F1_Score:",metrics.f1_score(y_test, y_pred, labels=np.unique(y_pred),  average = 'weighted'))
print("Confusion Metrics:",metrics.confusion_matrix(y_test, y_pred))
print("Mean_Squared_Error:",metrics.mean_squared_error(y_test, y_pred))


Accuracy: 0.9746666666666667
F1_Score: 0.9746666666666667
F1_Score: 0.9746113216045458
F1_Score: 0.9746732351798014
Confusion Metrics: [[378   3   0   0]
 [  5 361   8   0]
 [  0  13 357   3]
 [  0   0   6 366]]
Accuracy: 0.784
F1_Score: 0.7840000000000001
F1_Score: 0.7849795162099201
F1_Score: 0.7839750193064944
Confusion Metrics: [[106  13   0   0]
 [ 18  94  13   1]
 [  1  32  83  11]
 [  0   1  18 109]]
Mean_Squared_Error: 0.234


C:\Users\Dell\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
